sudo: false
dist: trusty
language: ruby
rvm:
  - "1.9.3"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"

cache:
  bundler: true
before_install: gem update bundler
script:
  - bundle exec rake
  - if ruby -e 'exit RUBY_VERSION >= "2.0.0"' ; then bundle exec rubocop ; fi
